### ISSUE TITLE
Is there any pre-trained model?

### ISSUE THREAD

**Issue by readable-ko** [nestiank/action-recognition-cnn-bd-lstm#2]
Am studying Alexnet + BD-LSTM with your code!
in your code loaded pre-trained model with model.load_state_dict(torch.load("./data/crnn.pth")) that is not on Github

can i get it? or where can i get it?

**Comment by nestiank** [comment]
Unfortunately, I did not made one.

**Comment by readable-ko** [comment]
알려주셔서 감사합니다!
